<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo>
        <plugin
            filename="libignition-gazebo-mecanum-drive-system.so"
            name="ignition::gazebo::systems::MecanumDrive">

            <!-- Wheel Information -->
            <front_left_joint>left_wheel_joint</front_left_joint>
            <front_right_joint>right_wheel_joint</front_right_joint>
            <back_left_joint>left_back_wheel_joint</back_left_joint>
            <back_right_joint>right_back_wheel_joint</back_right_joint>

            <wheelbase>${wheel_offset_x*2}</wheelbase>
            <wheel_separation>${wheel_offset_y*2}</wheel_separation>
            <wheel_radius>${mecanum_wheel_radius}</wheel_radius>

            <odom_publish_frequency>50</odom_publish_frequency>
            <topic>cmd_vel</topic>
            <odom_topic>odom</odom_topic>
            <tf_topic>/tf</tf_topic>
            <frame_id>odom</frame_id>
            <child_frame_id>base_link</child_frame_id>


        </plugin>


        <plugin filename="libignition-gazebo-joint-state-publisher-system.so"
            name="ignition::gazebo::systems::JointStatePublisher">
            <topic>joint_states</topic>
            <joint_name>left_wheel_joint</joint_name>
            <joint_name>right_wheel_joint</joint_name>
            <joint_name>left_back_wheel_joint</joint_name>
            <joint_name>right_back_wheel_joint</joint_name>
        </plugin>
    </gazebo>


</robot>